config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :restaurants do
    resources :reviews
  end
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    belongs_to :user
    has_many :reviews

    validates_presence_of :name, :description, :contactInfo, :location


    def self.search(search)
        where("name LIKE ? OR location LIKE ?", "%#{search}%", "%#{search}%")
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :restaurants
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def index
        if params[:search]
            @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
        else
            @restaurants = Restaurant.all.order("created_at DESC")
        end
    end

    def show
        if @restaurant.reviews.blank?
            @average_review = 0
        else
            @average_review = @restaurant.reviews.average(:rating).round(2)
        end
    end

    def new
        @restaurant = current_user.restaurants.build
    end

    def create
        @restaurant = current_user.restaurants.build(restaurant_params)

        if @restaurant.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @restaurant.update(restaurant_params)
            redirect_to restaurant_path(@restaurant)
        else
            render 'edit'
        end
    end

    def destroy
        @restaurant.destroy
        redirect_to root_path
    end

    private
        def restaurant_params
            params.require(:restaurant).permit(:name, :description, :contactInfo, :location)
        end

        def find_restaurant
            @restaurant = Restaurant.find(params[:id])
        end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :find_restaurant
    before_action :find_review, only: [:edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit]

    def new
        @review = Review.new
    end

    def create
        @review = Review.new(review_params)
        @review.restaurant_id = @restaurant.id
        @review.user_id = current_user.id

        if @review.save
            redirect_to restaurant_path(@restaurant)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @review.update(review_params)
            redirect_to restaurant_path(@restaurant)
        else
            render 'edit'
        end
    end

    def destroy
        @review.destroy
        redirect_to restaurant_path(@restaurant)
    end

    private
        def review_params
            params.require(:review).permit(:rating, :comment)
        end

        def find_restaurant
            @restaurant = Restaurant.find(params[:restaurant_id])
        end

        def find_review
            @review = Review.find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantReview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Restaurant Review", root_path, class: "navbar-brand" %>
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants" %>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Add Restaurant", new_restaurant_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :contactInfo, label: "Contact Info" %>
    <%= f.input :location %>
    <%= f.button :submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit Book</h2>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<% if @restaurants.present? %>
    <% @restaurants.each do |restaurant| %>
        <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <% end %>
<% else %>
    <p>There are no restaurants with the name or location of <%= params[:search] %>.</p>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="container">
    <div class="row">
        <h2><%= @restaurant.name %></h2>

        <h4>Average Rating
            <span class="average-review-rating" data-score="<%= @average_review %>"></span>
        </h4>
        <p>Based on <%= @restaurant.reviews.count %> reviews</p>
        <br></br>

        <p><%= @restaurant.description %></p>
        <p><%= @restaurant.contactInfo %></p>
        <b></br>
    </div>

    <div class="row">
        <%= button_to "Back", root_path, method: :get %>

        <% if user_signed_in? %>
            <% if @restaurant.user_id == current_user.id %>
                <%= button_to "Edit", edit_restaurant_path(@restaurant), method: :get %>
                <%= button_to "Delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?" } %>
            <% end %>
        <% end %>
        <br></br>
    </div>

    <div class="row">
        <h4>Reviews</h4>
        <% if user_signed_in? %>
            <%= button_to "Add Review", new_restaurant_review_path(@restaurant), method: :get %>
        <% end %>
        <%= render @restaurant.reviews %>
    </div>
</div>

<script>
    $('.review-rating').raty({
        readOnly:true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });
</script>

<script>
    $('.average-review-rating').raty({
        readOnly:true,
        score: function() {
            return $(this).attr('data-score');
        },
        path: '/assets/'
    });   
</script>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @restaurant.reviews.build]) do |f| %>
    <div id="rating-form">
        <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>

<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
</script>

app/views/reviews/_review.html.erb
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>

<% if user_signed_in? %>
    <% if review.user_id == current_user.id%>
        <div>
            <%= link_to "Edit", edit_restaurant_review_path(review.restaurant, review), class: "btn btn-primary" %>
            <%= link_to "Delete", restaurant_review_path(review.restaurant, review), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-sm" %>
        </div>
    <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= simple_form_for([@restaurant, @review]) do |f| %>
    <div id="rating-form">
        <label>Rating</label>
    </div>
    <%= f.input :comment %>
    <%= f.button :submit %>
<% end %>

<script>
    $('#rating-form').raty({
        path: '/assets/',
        scoreName: 'review[rating]'
    });
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>